### ISSUE TITLE
Flutter Color as field failed generation

### ISSUE THREAD

**Issue by Solido** [google/built_value.dart#513] opened 2018-09-28 06:39 UTC
Using ` Color get color;` error to

```
import 'package:built_value/built_value.dart';
import 'dart:ui';

part 'myclass.data.g.dart';

abstract class MyClass implements Built<MyClass, MyClassBuilder> {

  String get name;
  bool get completed;
  Color get color;

  @nullable
  String get description;

  MyClass._();

  factory MyClass([updates(MyClassBuilder b)]) = _$MyClass;
}
```

`
Please make the following changes to use BuiltValue:

1. Make field color have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
[`

I've try using dart:ui or flutter/material as import, Type is recognised by the IDE but not when using built_value. Not sure what I missed.

Thank you.

**Comment by Solido** [comment] 2018-09-28 09:50
I used the int color.value as replacement.
it does however lead to instantiate new Color object each time ...

**Comment by davidmorgan** [comment] 2018-10-03 16:18
Closing this as a duplicate of https://github.com/google/built_value.dart/issues/282

**Comment by MrCreeper1008** [comment] 2019-10-31 02:38
What version of `build_runner` fixed this issue? I just installed this package with `built_value: ` but im still getting the same issue. Thank you!

**Comment by davidmorgan** [comment] 2019-10-31 08:49
This was the commit to `package:build`:

https://github.com/dart-lang/build/pull/2501

I think it's in the latest version, `1.2.1`. It looks like that means `build_runner` `1.7.1` or higher.

**Comment by MrCreeper1008** [comment] 2019-10-31 12:59
Unfortunately I got the same error :(  

I pinned `build_runner` on version `1.7.1`:  
```
build_runner: 1.7.1
```   
Here is the code:  
```dart
import 'package:built_value/built_value.dart';
import 'package:flutter/widgets.dart' show Color;

part 'theme.g.dart';

abstract class Theme implements Built<Theme, ThemeBuilder> {
  String get fontFamily;
  Color get primaryColor;
  Color get textColor;
  Color get backgroundColor;

  Theme._();
  factory Theme([void Function(ThemeBuilder) updates]) = _$Theme;
}
```  
One of the errors:  
```
1. Make field primaryColor have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```

**Comment by davidmorgan** [comment] 2019-10-31 13:02
Have filed an issue over at `package:build` :)

Thanks.

**Comment by MrCreeper1008** [comment] 2019-10-31 13:03
Thank you so much!

**Comment by jakemac53** [comment] 2019-10-31 13:54
Copying comment from that issue, the fix is in build_resolvers not the build or build_runner, you will need version 1.2.1 of build_resolvers or greater.

**Comment by MrCreeper1008** [comment] 2019-10-31 13:56
So that means i need to explicitly install `build_resolvers`? Does `built_value` (or `build_runner`) not specify its own version of `build_resolvers`?

**Comment by jakemac53** [comment] 2019-10-31 14:00
You should be able to do a normal `pub upgrade` (for `flutter packages pub upgrade`) - it is a transitive dependency of build/build_runner. 

The output of that  command should show you the versions that were selected so as long as you get at least version `1.2.1` you should be good. If you don't get that version you would have to figure out why - one of the easier ways to do that would be to add the dependency temporarily and re-run the command.

**Comment by MrCreeper1008** [comment] 2019-10-31 20:31
Upgraded packages. `build_runner` is on `1.7.1` and `build` on `1.2.1`, but I am still having the same issue.

**Comment by jakemac53** [comment] 2019-10-31 20:36
What is the build_resolvers version though?

**Comment by MrCreeper1008** [comment] 2019-10-31 20:37
On 1.2.1

**Comment by jakemac53** [comment] 2019-10-31 20:40
And are you running `flutter pub run build_runner ...` or `pub run build_runer ...`?

**Comment by MrCreeper1008** [comment] 2019-10-31 20:41
`flutter pub run build_runner build`

**Comment by jakemac53** [comment] 2019-10-31 20:46
I just tried this for the `examples/hello_world`, adding the theme example above as `lib/theme.dart` and I got the following theme.g.dart file https://gist.github.com/jakemac53/9260b9b1c6ddd8ed53273bb8afb46359.

That looks like it worked to me - so something else might be going on. If that doesn't look like what is expected please let me know.

Can you try deleting your `.dart_tool/build_resolvers` directory as well?

**Comment by MrCreeper1008** [comment] 2019-10-31 20:59
So I tried:  
1. Deleting `.dart_tool` in my existing project;
2. Creating a new project, installing the packages, copying the class, and running build; and
3. restarting my computer.  

I am having issues in both projects, and the issue persists after the reboot :(

**Comment by jakemac53** [comment] 2019-11-01 15:36
@MrCreeper1008 what flutter version? Can you provide your entire `pubspec.lock` file? Ideally for the simplest example (the new project with the class copied).

**Comment by MrCreeper1008** [comment] 2019-11-01 15:58
Absolutely! I am on Flutter `1.9.1+hotfix6`. [Here](https://gist.github.com/MrCreeper1008/40209abce5265e37d5cff5153988a3f7) is the lock file for the new project I created.

**Comment by jakemac53** [comment] 2019-11-01 16:14
Ok - good news is I was able to reproduce the issue with that flutter version and pubspec.lock! Now to try and find the problem :).

**Comment by MrCreeper1008** [comment] 2019-11-01 16:15
Thank you so much for the help!

**Comment by jakemac53** [comment] 2019-11-01 16:18
Fyi I re-opened the build issue that @davidmorgan filed based on this https://github.com/dart-lang/build/issues/2528. I might do some followup there that I don't copy here but I will update this thread as well once the issue is resolved one way or the other.

**Comment by MrCreeper1008** [comment] 2019-11-01 16:19
Thank you! Will subscribe to that issue as well.

**Closed** 2020-04-13 08:39 UTC
