### ISSUE TITLE
A way to specify default values

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#212] opened 2017-09-05 09:21 UTC
Is there a way to specify default values for fields that are not `@nullable`?

**Comment by davidmorgan** [comment] 2017-09-05 09:39
There are a couple of ways.

If you write the builder by hand, you can set the default there, by setting a default value for the field in the builder. This sets a default for everything which goes via a builder, which includes deserialization.

Possibly easier although less correct is to make your factory set defaults:

```
  factory Account([updates(AccountBuilder b)]) = _$Account;
```

becomes

```
  factory Account([updates(AccountBuilder b)]) =>
      new _$Account((b) => b..name = 'default'..update(updates));
```

note however that this only works for instances created via that factory, which does _not_ include deserialization.

There may be room for improvement here now that writing the builder by hand isn't required.

**Comment by zoechi** [comment] 2017-09-05 10:03
Taking default values from an annotation in the generated builder would be really great.

**Comment by davidmorgan** [comment] 2017-09-05 10:18
Annotations are awkward because they can only contain `const` values -- so they only solve part of the problem. I'd want a solution for non-const values too.

The only thing that comes to mind is to have you declare the non-const value as a static final field and reference it:

```
static final BuiltList<String> oneTwoThree = new BuiltList<String>('one', 'two', 'three');

@defaultValue(#oneTwoThree)
BuiltList<String> get values;
```

...which would work but isn't exactly beautiful.

A more magic solution would be to simply take the default from any static final fields prefixed `default`. So `defaultValues` would automatically be the default. Not sure how I feel about this either, but it would save some boilerplate.

**Comment by davidmorgan** [comment] 2017-09-05 10:19
Another way would be to let you declare a default _instance_.

final Account defaultAccount = ...

@defaultInstance(defaultAccount)
class Account {
}

... this might work.

**Comment by zoechi** [comment] 2017-09-05 10:35
What about being able to add a static method that returns a builder that is then called by the generated builder and then updated with passed values. 
This would allow to define default values for any number of properties.
I don't know how serialization can work with that.

**Comment by davidmorgan** [comment] 2017-09-05 11:04
Yes, you're right, it would have to be a builder. (Since you might not provide values for all non-nullable fields). It can work for serialization too.

Sounds like a feature request :) thanks!

**Comment by rspilker** [comment] 2017-09-16 22:07
The trick we use in [lombok](https://projectlombok.org) (**Java**) is to have a final field with an initializer and an annotation, in this case @Builder.Default. We then use that initialization expression in the builder, but only if no value was set, to make sure it is only executed once.

In **dart**, it would look something like this:

```dart
abstract class Foo implements Built<Foo,FooBuilder> {
  @builderdefault
  final int value = -1;

  Foo._();
  factory Foo([updates(FooBuilder b)]) = _$Foo;
}
```

One potential problem I see in **dart** is that the expression would need to be resolved in the context of the class Foo.

Possibly, you can use a static field:
```dart
abstract class Foo implements Built<Foo,FooBuilder> {
  @builderdefault
  static final int _value = -1;
  int get value;

  Foo._();
  factory Foo([updates(FooBuilder b)]) = _$Foo;
}
```

But then you you can no longer base the default value on the values of other fields.

In my case, I would like to be able to express the following (pseudocode):

```dart
abstract class Image {
  String get imageUrl;
  String get thumbnailUrl [defaults to] imageUrl;
}
```

**Comment by zoechi** [comment] 2017-09-17 12:27
Currently I use a static getter like
```dart
static CategoryStateBuilder get defaultValue => new CategoryStateBuilder()
    ..loadChunkSize = defaultLoadChunkSize
    ..defaultView = new PagingInfo<Category>.defaultValue().toBuilder();
```
Where generic type parameters are required, I use a factory constructor (like shown with `PagingInfo` because there is no way to pass them using a getter or static method.

Currently I need to explicitly use such a getter or constructor to get a preinitialized instance or builder.  I'd prefer to be able to have such a getter used by built_value implicitly.

A method like

```dart
@defaultBuilder
static CategoryStateBuilder  defaultValue(dynamic updates(CategoryStateBuilder b)) => b
    ..loadChunkSize = defaultLoadChunkSize
    ..defaultView = new PagingInfoBuilder<Category>();
```
that will be called automatically by built_value after a new builder is created
would work well for me.

**Comment by davidmorgan** [comment] 2017-09-20 08:56
Thanks for the input Roel. Having non-static fields wouldn't work -- the fields themselves would be problematic for the generated classes; we can only add code in source_gen, not modify it.

Static fields would work but seem somewhat awkward.

I hadn't thought about setting defaults based on other values. One way to support this would be to declare, rather than a default instance or a default builder, a default "updates":

```
@defaults
static Updates<FooBuilder> defaults = (FooBuilder b) => b..thumbnailUrl ??= b.thumbnail;
```

this would run when you call "build". Having the ability to set defaults based on other fields or computation is kind of nice; but it's awkward that you have to use `??=` to avoid overwriting fields.

We could have _two_ `updates`, one that applies immediately when the builder is created and one that applies when you call `build`. I'm not sure this is especially clear, though.

**Comment by davidmorgan** [comment] 2017-09-20 08:58
Thanks Günter. Yeah, I think that's a good way to go -- it's just missing the ability to set defaults based on  other fields which Roel was asking for. But for most cases it seems a good fit.

**Comment by zoechi** [comment] 2017-09-20 09:38
Not sure what you mean with "other fields". 

Fields that are already set in the builder?

If this is not meant, then depending values could be calculate inside the method
```
@defaultBuilder
static CategoryStateBuilder  defaultValue(dynamic updates(CategoryStateBuilder b)) {
   final x = 5;
   final y = 3;
   b
    ..x = x
    ..y = y
    ..z = x * y;
}
```
also other static fields could be referenced.

**Comment by davidmorgan** [comment] 2017-09-26 11:30
Right, fields that are already set in the builder.

I think we can support both. I'll try to take a look soon...

**Comment by zoechi** [comment] 2017-09-26 11:53
Where would the values in the builder come from? Shouldn't the default value do the first initialization that can be overridden by later steps?

**Comment by davidmorgan** [comment] 2017-09-26 12:15
Yeah, we need two: one which runs first (defaults) and one which runs last (derived defaults). You usually don't need the second.

**Comment by zoechi** [comment] 2017-09-26 12:18
I think I understand now.

**Comment by davidmorgan** [comment] 2017-10-30 14:46
Having thought about this some more, I think providing a nicer way to specify defaults is _not_ the way to go.

The 'most correct' way to specify defaults is to write an abstract builder yourself:

```
abstract class ValueWithDefaults
    implements Built<ValueWithDefaults, ValueWithDefaultsBuilder> {
  int get anInt;
  @nullable
  String get aString;
  SimpleValue get value;

  factory ValueWithDefaults([updates(ValueWithDefaultsBuilder b)]) =
      _$ValueWithDefaults;
  ValueWithDefaults._();
}

abstract class ValueWithDefaultsBuilder
    implements Builder<ValueWithDefaults, ValueWithDefaultsBuilder> {
  int anInt = 7;

  @nullable
  String aString;
  SimpleValueBuilder value = new SimpleValue((b) => b..anInt = 3).toBuilder();

  factory ValueWithDefaultsBuilder() = _$ValueWithDefaultsBuilder;
  ValueWithDefaultsBuilder._();
}
```

Writing the builder yourself like this is awkward, which is why I haven't recommended it strongly so far. But if you get past the awkwardness, it has other big benefits. You can add helper methods to the builder, and have it implement interfaces. These both make the whole value+builder pattern significantly more powerful.

It also works better with your IDE -- there will be no unresolved symbols while waiting for generation to run.

So I think this is the right way to do it. The only question is what to do about the fact that it's annoying to have to write the builder (interface) yourself. Fortunately I have plan here; I'd like to write an analyzer plugin, like the one angular has. This will provide an "auto fix" in your IDE for built_value, making it easy to keep that explicit builder interface there. You will then always have a place to add defaults -- and it will be clear how they work.

What do you think, please?

I'm hoping to look at this (the analyzer plugin) ~soon, no promises, though :)

**Comment by zoechi** [comment] 2017-10-30 19:40
Could it not just generate that builder from a few annotations, to get the most common cases covered?

**Comment by davidmorgan** [comment] 2017-10-31 09:16
I agree that makes sense when the "explicit builder" pattern is more annoying, as now.

But I hope that with an analyzer plugin it won't be annoying. Then, providing two ways to do the same thing will just be confusing. Particularly if you have to switch to the explicit builder to get some features -- which you always will, since we're unlikely to support adding code to the builder via annotations.

Of course, if the analyzer plugin doesn't work out, this will need a rethink :)

**Comment by giraldeau** [comment] 2017-12-11 02:07
Right now, I catch ArgumentError while deserializing and return the default value in that case. Effective, but a bit awkward.

**Comment by giraldeau** [comment] 2017-12-11 02:33
Actually, inside the generated deserialize() replacing `final result = new SimpleValueBuilder();` with `final result = new SimpleValue().toBuilder();` would take into account the default values provided in the factory constructor.

**Comment by tobytraylor** [comment] 2018-07-31 18:35
I know you appear to have already gone the customer builder route but i thought i'd throw in a vote for a solution more like @giraldeau.  Can't we have the code generation use the zero parameter constructor? Seems the constructor with optional builder that initializes the members is fairly elegant and you lose that elegance.

**Comment by BerndWessels** [comment] 2018-09-13 02:55
Is there a solution to this @davidmorgan ?

I can't figure out how to achieve a default value - the example you gave here doesn't seem to work.

**Comment by davidmorgan** [comment] 2018-09-13 12:03
There's definitely a way to get defaults :) ... what issue did you run into with the example? I'll see if I can fix it.

**Comment by BerndWessels** [comment] 2018-09-13 20:43
Thanks @davidmorgan 

Here is an example class

```dart
abstract class MenuItem implements Built<MenuItem, MenuItemBuilder> {
  static Serializer<MenuItem> get serializer => _$menuItemSerializer;

  factory MenuItem([updates(MenuItemBuilder b)]) = _$MenuItem;

  MenuItem._();

  double get count;

  String get currency;

  String get currencySymbol;

  @nullable
  String get description;

  @nullable
  int get endTime;

  @nullable
  String get image;

  double get price;

  bool get soldOut;

  @nullable
  int get startTime;

  String get title;

  BuiltList<MenuItemVariation> get variations;
}
```

The only way I could get the `count` property to have a `default value` was to follow your earlier advice and add a class like this

```dart
abstract class MenuItemBuilder implements Builder<MenuItem, MenuItemBuilder> {
  double count = 1.0;

  String currency;

  String currencySymbol;

  @nullable
  String description;

  @nullable
  int endTime;

  @nullable
  String image;

  double price;

  bool soldOut;

  @nullable
  int startTime;

  String title;

  ListBuilder<MenuItemVariation> variations;

  factory MenuItemBuilder() = _$MenuItemBuilder;
  MenuItemBuilder._();
}
```

In this class I actually have to repeat all properties again, even though I only need a default value for one of the properties.

This seems like a crazy overhead and since I am in the process of advocating for flutter in our big enterprise company such amount of boilerplate code and repetition would scare the crap out of inexperienced devs.

Also I thought the whole point behind build_runner is to create boilerplate automatically if necessary.

I there another way we can get default values easier (like @giraldeau mentioned) ?

Cheers
Bernd

**Comment by davidmorgan** [comment] 2018-09-14 15:18
I see--so it's not so much an issue with it working but an issue with the usability. That's fair enough :)

So the other option right now is to write a factory constructor that sets defaults. The main downside with this approach is it won't set defaults when deserializing. The defaults should be present on the wire, though, so this is maybe not a major downside.

**Comment by BerndWessels** [comment] 2018-09-18 20:41
@davidmorgan Providing the default values from the backend is a messy solution in many cases, since the default values are often client side only support/helper properties (i.e. `selected=false`). My data comes from firestore and I don't want to polute the database with unnecessary properties.

I see 2 options, either the code generator understands something like `@default` and generates the boilerplate code, or the code generator gets a small modification to support the factory constructor in deserialization ( like mentioned by @giraldeau ):
> Actually, inside the generated deserialize() replacing final result = new SimpleValueBuilder(); with final result = new SimpleValue().toBuilder(); would take into account the default values provided in the factory constructor.

Do you think either of these solutions can be done?

**Comment by tobytraylor** [comment] 2018-09-18 21:27
I once again would like to vote in favor of the having the generator use the factory constructor.  Much more elegant than implementing your own builder.

**Comment by lucyget** [comment] 2018-10-11 01:10
Would it be possible to make a change such that a custom builder only needs to specify the fields you want to give default values to?

**Comment by adamlofts** [comment] 2018-10-11 13:19
Could we have an annotation for default const values? Its not a complete solution but probably solves 80% of the use cases.

**Comment by davidmorgan** [comment] 2018-10-15 15:54
@tobytraylor Unfortunately having the generator use the factory constructor is problematic, since we can't necessarily identify the different variations on the factory constructor that you might want to write. (Currently you're allowed to write more or less anything).

@lucyget Unfortunately making the custom builder only specify a subset of fields doesn't work; when you write a custom builder it becomes the public API for the builder, any fields you don't specify are hidden. We could potentially introduce a _different_ way to write a custom builder which is _not_ used for the public API, but that seems over-complicated.

At this point I think an annotation may be the least painful way to go, after all...

**Comment by FranPitri** [comment] 2019-03-12 12:54
Hello! Any updates on this?

**Comment by davidmorgan** [comment] 2019-03-12 13:30
No update, sorry--but it's still on my TODO list.

**Comment by tobytraylor** [comment] 2019-03-12 20:40
Wait.  What about a annotation that identifies the factory constructor that you want the system to use?

**Comment by dougmill** [comment] 2019-04-27 08:59
Coming from how the [Immutables library](https://immutables.github.io/) for Java does it, and seeing from `@memoized` that the same approach is clearly possible here, this seems very obvious to me: Make an annotation that works exactly like `@memoized` except that it generates a setter.

Might even be better to make it implicit - that a getter in the value class with a defined body is automatically treated as defining a default value. If you don't go that route, then at least add a flag in `@BuiltValue` to enable that behavior to reduce boilerplate in classes that have many custom defaults (with a corresponding annotation or flag to override it for individual fields if needed).

Note that Immutables actually calculates and stores applicable default values eagerly on build, with an annotation to make it lazy, and has loop detection in the eager calculation to quickly throw if a field's default ends up depending on itself. Whether _these_ behaviors are worthwhile to implement is much less clear to me.

**Comment by dave26199** [comment] 2019-04-27 10:47
That sounds _much_ better than anything discussed so far. Thank you :)

My first thoughts on implementation: for non-nullable fields, this is easy: make either the generated constructor or the generated getter check for nulls and convert to the new default. This is indeed very close to the behaviour of `@memoized` fields.

The hard part is what to do with nullable fields. Note that `@memoized` already does not work well for nulls: null values are not memoized, they are computed over and over. (I have an issue open to address this somehow, possibly by throwing if a null is returned). My first thought is to simply not allow defaults for nullable fields: if a field is nullable, the default is null, end of story. Thoughts?

I'm excited about this--it's great to have a good answer at last--will see if I can get to implementing it soon :)

**Comment by dougmill** [comment] 2019-04-27 17:37
For memoized nullable fields, you could add a private boolean field to track whether the field's value has been calculated or not instead of relying on a special value. Alternatively, use a custom special value (suppressing type safety checks so you can use the same one for everything) rather than null.

For default values, if you make them computed eagerly on construction then the constructor can track what's been initialized and then let that info get dropped in the final end result because it's implicit that the built object has all of them initialized.

**Comment by dougmill** [comment] 2019-04-28 00:10
As I recall, Immutables handles this by defining an additional private subclass of the value class, used for the transition from builder to built. In this transitional class, each field that has a default value has its state tracked as not started, in progress, or fully initialized. Any field that had a value explicitly set in the builder gets that value and is fully initialized. Then the constructor calls each of the defaultable getters.

Each of these getters has this logic:

1. If fully initialized, return the value.
2. If in progress, throw an exception because there's a cyclic dependency.
3. Set state to in progress.
4. Call the superclass getter to find the default value.
5. Store the computed value and set state to fully initialized.
6. Return the value.

Additionally, the builder has a bitfield tracking which fields have been explicitly set, which allows it to distinguish between "not set" and "set to null".

**Comment by davidmorgan** [comment] 2019-05-31 13:49
I had a quick look at this today.

Unfortunately the ways I can think of implementing this are incompatible with the fact that we suggest using the private constructor of value class for validation.

```
abstract class ValidatedValue
    implements Built<ValidatedValue, ValidatedValueBuilder> {
  static Serializer<ValidatedValue> get serializer =>
      _$validatedValueSerializer;

  int get anInt;
  @nullable
  String get aString;

  factory ValidatedValue([void Function(ValidatedValueBuilder) updates]) =
      _$ValidatedValue;

  ValidatedValue._() {
    if (anInt == 7) throw StateError('anInt may not be 7');
  }
}
```

Anything where we lazily (including in the constructor body) check for and assign default values runs too late, after the value class constructor has run.

This also prevents using a private intermediate type just to get the defaults.

We could get around this by asking for another, empty constructor for these cases, but that's pretty awkward.

The approach has other issues, though: if we use the constructor of the generated value type to initialize with defaults, it forces the fields to be non-final. If we use an intermediate type, it means there is more than one implementation of the type, which cuts down on optimizations the runtimes can do.

Fields with nested builders are also awkward, because we auto-create builders for those when you access the getters; an auto-created builder would fight with the default. What we really want for those is to initialize the nested builder, but we can't access the value from the builder.

I'm afraid this still needs more thought :/

**Comment by dougmill** [comment] 2019-06-10 19:49
Another possibility is to move the validation to a separate private function, designated either by a specific function name or by annotation. This would not strictly be a breaking change, as the old approach would still work, and the new approach would only be necessary for people who are writing new code to use the new default values feature.

My other idea is to actually copy the source code implementation of the default value functions to use in the builder or intermediate value class. Copying any member functions or derived fields that the default value depends on would also be needed, might be simpler to just copy the entire class except the constructors. I briefly considered that access to outside functions called might be an issue, but dart has no access constraint narrower than a whole library and the generated code is in the same library.

**Comment by wemped** [comment] 2019-07-01 19:18
The original question has to do w/ fields that are specifically not `@nullable`, does that mean there is a supported way to have default values for `@nullable` fields?

**Comment by Lootwig** [comment] 2019-07-12 08:33
@wemped if this is the case, then it must be one of the worst documented features of this package. I spent a while now looking for exactly that and will now resolve to try to making one of the solutions presented here work.

**Comment by cpboyd** [comment] 2019-07-27 19:13
@wemped I also read into @zoechi's initial comment, but sadly I think it's just that they have a default value of `null`.

Cf:
https://github.com/google/built_value.dart/blob/9a865815d5e265b06e3571b0ac0deb4656b189fc/example/lib/example.dart#L12

**Comment by vitor-gyant** [comment] 2019-08-07 17:05
So, is there a way to specify default values for nullable fields ?

**Comment by Lootwig** [comment] 2019-08-07 19:58
@vitor-gyant read my reply https://github.com/google/built_value.dart/issues/212#issuecomment-510801406

**Comment by vitor-gyant** [comment] 2019-08-08 08:56
@Lootwig thanks. it seems the only way is to create a custom builder and init the value there correct ?

**Comment by davidmorgan** [comment] 2019-08-08 09:05
You can also set defaults in the factory, as per my initial reply waaaaay up in the thread :)

**Comment by vitor-gyant** [comment] 2019-08-08 09:30
@davidmorgan Yes but it doesn't work when calling deserialise which is my use case.

**Comment by davidmorgan** [comment] 2019-08-08 10:08
Yes, for defaults to apply on deserialization the custom builder is the only thing that works.

**Comment by devkabiir** [comment] 2019-08-31 14:29
Would something like this work?

```dart
// my_built_value.dart

abstract class MyBuiltValue
    implements Built<MyBuiltValue, MyBuiltValueBuilder> {
        /// Field with no default value
        /// Throw `DeserializationError` if `null` value supplied
        String get aField;

        /// Field with no default value
        /// Allows `null` value
        @nullable
        String get nullableField;

        /// Field with default value
        /// Use the default value (`super.defaultValueField`) if `null` value supplied
        /// For this getter, we're explicitly marking it as a built-value field
        /// This is to tell the generators that, even though this is not an abstract getter
        /// We still want to use it as a serializable field
        @BuiltValueField()
        String get defaultValueField => 'Hello world';
    }


// my_built_value.g.dart

class _$MyBuiltValueImpl extends MyBuiltValueImpl {
  /// We make all fields private to make code generation easy
  final String _aField;
  final String _nullableField;
  final String _defaultValueField;

  /// Then we generate getters for all fields
  @override
  String get aField => _aField;
  @override
  String get nullableField => _nullableField;

  /// We add `?? super.fieldname` for a field with non-abstract super getter
  @override
  String get defaultValueField => _defaultValueField ?? super.defaultValueField;

}

```

Now using this build_value

```dart
// usage_example.dart

/// Manully constructed built_value with required fields
final myValue = MyBuiltValue((b)=> b.aField = "some value"); // This should have default values as well

final serialzied = serializers.serialize(myValue); // This should also produce output with default values

final deserialized = serializers.deserialize(serialzied) // Should work as well

final fromWire = serializers.deserialize({/* required fields*/ "aField": "aValue" })

/// [fromWire] should also have the default value availabe

```

I think if the above van be made possible, this should solve most use cases.

Another use case of `@nullable` fields with default values can also use this approach

@davidmorgan, What do you think?

**Comment by devkabiir** [comment] 2019-09-13 23:43
I had a quick run at this today,
Based on the suggestion provided [above](https://github.com/google/built_value.dart/issues/212#issuecomment-526834876) I have an initial implementation ready here https://github.com/devkabiir/built_value.dart/tree/default_values, I'd appreciate some feedback on whether this approach is valid and should be continued further.

**Comment by davidmorgan** [comment] 2019-09-17 16:26
Sorry for the slow response. Thanks for taking a look.

Let me see if I understood correctly. The idea is that for nullable fields, you can use `??` in the generated implementation to return the super value (the default) if the set value is null.

But, it doesn't do anything for non-nullable fields?

Thanks :)

**Comment by devkabiir** [comment] 2019-09-17 17:41
@davidmorgan  The idea is to mark any(including interfaces/mixins) non-abstract getters with `BuiltValueField(serialize:true)` to allow them to be serializable as well as generate setters/getters in the generated `Builder` implementation. By default `serialize:true` so only `@BuiltValueField()` is required.

This includes both nullable and non-nullable fields. In my original comment I was just showing different scenarios. I should've done a better job of that.

Here is the working example along with the generated code. [value.dart](https://github.com/devkabiir/built_value.dart/blob/default_values/example/lib/values.dart#L98-L124), [values.g.dart](https://github.com/devkabiir/built_value.dart/blob/default_values/example/lib/values.g.dart#L759-L896).

This idea makes the following possible

```dart

abstract class MyValue {
/// This field will not be included in the serialized output, and in builders
/// This is how the generator currently works.
String get string1 => 'default-value';

/// We mark a non-abstract getter with `BuiltValueField()`, this tells the generator to use this field in serializer, builder, and implementation generation
/// Default can be anything that the getter return;
@BuiltValueField()
String get string2 => 'test';

/// Since defaults are set using getters, they might be computed, we allow them to be null as well by marking with `@nullable`
/// IF this getter returns a `null` value but the field is not marked with `@nullable`, the usual `BuiltValueFieldNullError` is thrown
@BuiltValueField()
@nullable
String get string3 => String.fromEnvironment("I don't exits");

/// This field is nullable and it also does not have a default
@nullable
String get string4;

/// This field is nullable and it actually has a non-null default
@BuiltValueField()
@nullable
String get string5 => 'hello';


/// This field's default is computational heavy, so we also support `memoized`
@BuiltValueField()
@memoized
String get string6 => heavyComputation();

}
// No actual updates applied
final builder = MyValueBuilder()
// In our example string2 is required. But it has a default
// So this will work
final value = builder.build()

// This will work as well
final value2 = MyValue()
```

Nested `Built` fields with properties having a default is also supported.

Currently manually defining a `Builder` allows for setting default values. So this is also supported, since in this case the _behaviour_ of the builder is defined already. 

In my [implementation](https://github.com/devkabiir/built_value.dart/tree/default_values) all existing tests pass, But new tests must be added if this approach is to be taken further. This is backwards compatible. But it can be optimized and released as a breaking change as well.

**Comment by davidmorgan** [comment] 2019-09-23 10:40
Thanks. I see a couple of problems with this approach, unfortunately:

1. The `_silent` constructor can fail if you do any checking in `DefaultValue._`, which is the recommended place to add checks for fields. We'd need a reliable way to instantiate an 'incorrect' instance, which would mean forcing you to write an additional "no checks, don't use me" constructor for just this case.

2. If I read it correct, if a nullable field has a default, then there is no way to explicitly set it to null--it will get the default instead.

Any thoughts on these? Thanks. (And sorry for the slow response again).

**Comment by devkabiir** [comment] 2019-09-25 20:05
Hi, @davidmorgan 

I've removed the `_silent` workaround and added few examples and tests [here](https://github.com/devkabiir/built_value.dart/commit/e0854b5cedec482b975f4b5e404bfcb52f37f468). Please have a look at those, is that how this feature is intended to be used?

>  1. The `_silent` constructor can fail if you do any checking in `DefaultValue._`, which is the recommended place to add checks for fields. We'd need a reliable way to instantiate an 'incorrect' instance, which would mean forcing you to write an additional "no checks, don't use me" constructor for just this case.

I agree that the `_silent` approach is not very reliable, I was just trying things out.
Reason I felt we needed that is,
If there exists a `BuiltCollection` in `MyValue` class that has a default value, then we need this workaround to build upon those default values in the builder, otherwise the builder always creates an empty collection in case there wasn't a non-null value already present.
I don't have any ideas on how default values for BuiltCollections would work inside the Builder. Any thoughts on that? 


>  2. If I read it correct, if a nullable field has a default, then there is no way to explicitly set it to null--it will get the default instead.

This is essentially the same problem as `@memoized` getters returning a null value. I think the problem is the usage of `??` or `??=` operator. It will always return the right most non-null value.

My intended use case and POC implementation was originally for fields that are not `@nullable`. But I can see myself and many others wanting to have a default value for `@nullable` fields as well. 
In later cases, 
Either don't allow `@nullable` fields to have a default value. If a field can be `null`, then `null` is their default value.

Or,
One possible way to allow `@nullable` with defaults to be explicitly set to `null` is to generate additional flags which would track if the field was explicitly set to null in the Implementation class as well as the generated Builder. Example code:

```dart
class MyValue {
	  @BuiltValueField()
	  @nullable
	  String get nullableStringWithDefault => 'default'
}

class MyValueImpl extends MyValue {

/// If `true` then always return `null` for `nullableStringWithDefault`
final bool _nullableStringWithDefaultIsNull;

String _nullableStringWithDefault;

@override
String get nullableStringWithDefault => _nullableStringWithDefaultIsNull ? null : _nullableStringWithDefault ?? super.nullableStringWithDefault;

  MyValueImpl ._({String nullableStringWithDefault, bool nullableStringWithDefaultIsNull})
      : _nullableStringWithDefaultIsNull = nullableStringWithDefaultIsNull,
		_nullableStringWithDefault = nullableStringWithDefault,
        super._();

}


class MyValueBuilder {
  String _nullableStringWithDefault;
  bool _nullableStringWithDefaultIsNull;
  String get _nullableStringWithDefault => _$this._nullableStringWithDefault;
  // The setter for `@nullable` with defaults would check if the value is being set to
  // `null` explicitly
  set nullableStringWithDefault(String nullableStringWithDefault) {
    _$this._nullableStringWithDefault= nullableStringWithDefault
    _$this._nullableStringWithDefaultIsNull= nullableStringWithDefault==null;
  };

}


```

**Comment by devkabiir** [comment] 2019-10-01 18:22
Another possible way to allow `@nullable` with default value to be explicitly set to `null` is to use an additional "reference" object. Example: https://dartpad.dartlang.org/a1fd1ef2366fc27035dd7f4efc38764a

I probably somethings wrong in that code snippet but I hope it gets the idea across.

**Comment by davidmorgan** [comment] 2019-10-11 15:30
Sorry for continued lack of responses on my part. This is a hard problem. Hopefully I can find some time to work on `built_value` this quarter, and I'll try to dig into this problem.

**Comment by davidmorgan** [comment] 2019-10-25 14:09
Hi everyone,

I have a PR out to support setting defaults by adding an `_initializeBuilder` method to your value type. It works for value types and serialization.

https://github.com/google/built_value.dart/pull/731/files#diff-0495adf5d2e9dbde8ab38eae465d6ad1

The only caveat is that the generated `._` constructor taking named params doesn't use it. If you write a custom factory constructor that uses this generated constructor, you have to deal with defaults yourself. It's like that because named params have no way of working correctly with nullable fields, so we don't try.

The same PR adds a hook for modifying builders when `build` is called so you can do post-processing.

Thoughts, opinions? Does it look like this fills the gap in current functionality?

Thanks!

**Closed** 2019-10-28 09:26 UTC
Labels: p1 / feature request

**Comment by jamesderlin** [comment] 2019-10-28 19:49
Is there any documentation for `_initializeBuilder` (and `_finalizeBuilder`)?

**Comment by kuhnroyal** [comment] 2019-10-28 19:58
Look at the tests in the linked PR.

**Comment by jamesderlin** [comment] 2019-10-28 20:00
Yes, I can look at those, but that is not discoverable documentation.  People who don't already know about `_initializeBuilder`/`_finalizeBuilder` aren't going to know to look there.

**Comment by davidmorgan** [comment] 2019-10-29 09:42
No docs yet--was going to let the feature bake for a bit before promoting it, in case any tweaks are needed.

https://github.com/google/built_value.dart/issues/736

Thanks :)

**Comment by larssn** [comment] 2020-03-02 17:49
@davidmorgan What are the challenges involved with having defaults as annotations? I mean, defaults should be fairly static, so I figured it should be possible to have the codegen tool put the defaults in the .g.dart files?

**Comment by davidmorgan** [comment] 2020-03-03 12:54
@larssn Annotations can currently only contain `const` values, which is too limiting. For example, internationalized strings can't be const. I didn't want to have a partial solution for defaults :)

**Comment by phamnhuvu-dev** [comment] 2020-03-28 05:50
@davidmorgan I added this code and run build runner but still have error `This is forbidden; to allow it, mark "id" with @nullable`.
```dart
  static void _initializeBuilder(MessageBuilder builder) => builder
    ..id = ''
    ..userId = ''
    ..content = ''
    ..urlMedia = ''
    ..createdAt = DateTime(1970, 1, 1)
    ..type = MessageType.none
    ..localId = '';
```

**Comment by dave26199** [comment] 2020-03-28 06:20
@phamnhuvu-dev That should work--I suggest checking if the generated code (.g.dart) is up to date, it should change to call it for you.

**Comment by pqsky7** [comment] 2020-05-22 13:56
> @davidmorgan I added this code and run build runner but still have error `This is forbidden; to allow it, mark "id" with @nullable`.
> 
> ```dart
>   static void _initializeBuilder(MessageBuilder builder) => builder
>     ..id = ''
>     ..userId = ''
>     ..content = ''
>     ..urlMedia = ''
>     ..createdAt = DateTime(1970, 1, 1)
>     ..type = MessageType.none
>     ..localId = '';
> ```


It is worked, my code below:
```
  Something get something;
  bool get verified;
  static void _initializeBuilder(TestInfoBuilder builder) => builder
    ..verified = false;
```
with this code, you can even skip the orgin solution @dave26199 provided
```
  factory Account([updates(AccountBuilder b)]) =>
      new _$Account((b) => b..name = 'default'..update(updates));
```
It is good enough for me, the only problem is just little bit time cousmuing to find it...

**Comment by deadsoul44** [comment] 2021-01-23 19:50
How about if I want to initialize a generic field?
