### ISSUE TITLE
Nested Arrays/BuiltList

### ISSUE THREAD

**Issue by jimmyff** [google/built_value.dart#165] opened 2017-04-18 09:44 UTC
I think there might be an issue with deserialising nested arrays. My JSON object was giving the following error `Bad state: No builder for BuiltList<ScorePart>.` when deserializing the following JSON:
```
{
"scores" : [
      [
        {"field_label":"total", "field_type":"num", "field_value":"50"}
      ],
      [
        {"field_label":"total", "field_type":"num", "field_value":"100"}
      ]
    ]
}
```
My definition of scores:
```
  BuiltList<BuiltList<ScorePart>> get scores;
```

In my `serializers.g.dart`, it had generated this `BuilderFactory`:
```
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(BuiltList, const [const FullType(ScorePart)])
          ]),
          () => new ListBuilder<BuiltList<ScorePart>>())
```
I resolved the issue by a `BuilderFactory` to `serializers.dart` (not nested):
```
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(ScorePart)]),
          () => new ListBuilder<ScorePart>())
```

**Comment by dave26199** [comment] 2017-04-18 10:15
Thanks. Yes, this is an issue, and you found the right workaround. This is also related to issue

https://github.com/google/built_value.dart/issues/124 

-- the problem is that the generation is currently not smart enough to pick up the need for the builder factory in the case of nested collections and generics. The workaround is to add them by hand, as you discovered.

I will definitely fix this at some point -- it's a bit involved, though, particular for generics. Actually the nested collection case might be simpler. I'll take a look. Thanks!

**Comment by davidmorgan** [comment] 2017-12-19 14:15
Closing in favour of #124

**Closed by davidmorgan** 2017-12-19 14:15 UTC
