### ISSUE TITLE
@memoized doesn't work with mixins

### ISSUE THREAD

**Issue by avioli** [google/built_value.dart#734] opened 2019-10-28 02:32 UTC
```dart
import 'package:built_value/built_value.dart';

part 'memoization.g.dart';

mixin DerivedValueMixin {
  int get anInt;

  @memoized
  int get derivedValue {
    print('recompute derivedValue');
    return anInt + 10;
  }
}

abstract class DerivedValue
  with DrivedValueMixin
  implements Built<DerivedValue, DerivedValueBuilder>
{
  factory DerivedValue([updates(DerivedValueBuilder b)]) = _$DerivedValue;
  DerivedValue._();
}
```

`derivedValue` will never be memoized. No memoization code will be generated.

**Comment by avioli** [comment] 2019-10-28 02:59
It works as expected if the getter is defined within the abstract class itself.

I have a mixin I use as a "base", which then is used by way too many `Built` classes I feel comfortable copy/pasting the `@memoized` getter to.

**Comment by davidmorgan** [comment] 2019-10-28 09:06
Thanks for filing. This is a dupe of https://github.com/google/built_value.dart/issues/387. I'll take this as a +1 for that issue :)

**Comment by davidmorgan** [comment] 2019-10-28 09:07
(bumped it to p1, which will help remind me to take a look at it next time I do a batch of features).

**Closed by davidmorgan** 2019-10-28 09:06 UTC
