### ISSUE TITLE
serializers returns 'Object?' instead of 'Map<String, Object?>'

### ISSUE THREAD

**Issue by binajmen** [google/built_value.dart#1039] opened 2021-05-29 06:56 UTC
Hi,

I want to use `built_value` with `FlutterFire` (that is, firestore).

This is how I declared two methods `toFirestore` and `fromFirestore` and the serializers:
```dart
// place.dart

  Map<String, Object?> toFirestore() {
    return serializers.serializeWith(Place.serializer, this);
  }

  static Place? fromFirestore(Map<String, dynamic> json) {
    return serializers.deserializeWith(Place.serializer, json);
  }

// serializers.dart

@SerializersFor([
  Place,
])
final Serializers serializers = _$serializers;

final Serializers standardSerializers =
    (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

// serializers.g.dart

// GENERATED CODE - DO NOT MODIFY BY HAND

part of serializers;

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()).build();

// ignore_for_file: ...
```
I get the following error for the method `toFirestore`:
```
A value of type 'Object?' can't be returned from the method 'toFirestore' 
because it has a return type of 'Map<String, Object?>'
```
Any help would be greatly appreciated!

For your information, I'm using it with `withFirestore` to allow type-safety while using Firestore:
```dart
  final placesRef =
      FirebaseFirestore.instance.collection('places').withConverter<Place>(
            fromFirestore: (snapshot, _) => Place.fromFirestore(snapshot.data()!),
            toFirestore: (place, _) => place.toFirestore(),
          );
```

**Comment by davidmorgan** [comment] 2021-05-31 06:30
I think you'll need to cast the result, e.g. `as Map<String, Object?>`.

**Comment by binajmen** [comment] 2021-05-31 06:52
Han, it makes sense. I'm surprised all the examples were not mentioning this cast.. I'll try that as soop as possible!

Thank you for your answer :)

**Comment by davidmorgan** [comment] 2021-06-09 12:07
Closing for https://github.com/google/built_value.dart/issues/1049

**Closed by davidmorgan** 2021-06-09 12:07 UTC
Labels: question

**Comment by davidmorgan** [comment] 2021-06-14 12:56
This appears to be working as intended--`serializers` has no way to know that you're serializing something that results in a `Map`, so you'll have to cast it. (Or just return Object? and deal with the cast elsewhere). Sorry about that!
