### ISSUE TITLE
Upgrade build_config to 1.0.0

### ISSUE THREAD

**Issue by smkhalsa** [google/built_value.dart#1025] opened 2021-04-22 10:25 UTC
`build_config` now has a null-safe version (1.0.0) which is used by `build_runner` 2.0.0.

Can we upgrade `built_value` to use `build_config` ^1.0.0 so that it can be compatible with `build_runner` 2.0.0?

Thanks!

**Comment by davidmorgan** [comment] 2021-04-22 14:04
Thanks! I think I can get to this next week.

**Comment by ab36245** [comment] 2021-04-23 05:21
Great! This is biting me too, so allowing us to move to the latest build_runner will be a positive step.

**Comment by aarajput** [comment] 2021-04-27 06:00
Any update about this?

**Comment by allanclempe** [comment] 2021-04-29 05:05
+1

**Comment by Fraa-124** [comment] 2021-04-29 05:48
We're stuck on this so can't migrate to null safety

`Because build_runner >=2.0.0 depends on build_config >=1.0.0 <1.1.0 and built_value_generator 8.0.5 depends on build_config >=0.3.1 <0.5.0, build_runner >=2.0.0 is incompatible with built_value_generator 8.0.5.`

**Comment by allanclempe** [comment] 2021-04-30 00:49
@Fraa-124 this combination works for me. Not ideal overriding, but is a way to work around until this gets done.

```
dependencies:
  built_value: ^8.0.5
  built_collection: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.1
  built_value_generator: ^8.0.5

  
dependency_overrides:
  build_config: 1.0.0

```

**Comment by smkhalsa** [comment] 2021-05-03 16:30
@davidmorgan any update on the timeline for this? Thank you

**Comment by jscti** [comment] 2021-05-05 07:03
Even with the dependency_overrides, it fails with the flutter `integration_test` package because of build_runner :

Tried many overrides without success

Because no versions of built_value_generator match >8.0.5 <9.0.0 and built_value_generator 8.0.5 depends on analyzer ^1.5.0, built_value_generator ^8.0.5 requires analyzer ^1.5.0.
And because no versions of analyzer match >1.5.0 <2.0.0, built_value_generator ^8.0.5 requires analyzer 1.5.0.
And because analyzer 1.5.0 depends on crypto ^3.0.0 and every version of integration_test from sdk depends on crypto 2.1.5, built_value_generator ^8.0.5 is incompatible with integration_test from sdk.

**Comment by 7sergiy** [comment] 2021-05-05 10:28
Hi, @davidmorgan 

Have the same problem with built_value_generator ^8.0.5 and build_runner: ^2.0.2, - they are incompatible because of build_config. 

It is **very critical** issue. Could you please provide us with some time estimations when it'll be fixed? 

Thanks.

**Comment by dave26199** [comment] 2021-05-05 10:37
Sorry about that; I took a look today but hit some test timeouts, I need to
determine if they are caused by the version changes. I will try that
tomorrow.

**Comment by smkhalsa** [comment] 2021-05-10 08:59
@davidmorgan Just checking in on this. Any update? Thanks

**Comment by davidmorgan** [comment] 2021-05-10 11:45
Should already be fixed by https://github.com/google/built_value.dart/releases/tag/v8.0.6 -- please reopen if not. Thanks.

**Closed by davidmorgan** 2021-05-10 11:45 UTC
Labels: p2 / feature request
