### ISSUE TITLE
Using an empty mixin causes an error

### ISSUE THREAD

**Issue by twistedinferno** [google/built_value.dart#544] opened 2018-12-10 08:48 UTC
If I have an empty mixin (used for type aliasing) the build runner tries to build that file and fails (even though there is no reference to built value).

Including a file with the following code causes the problem

`mixin ToAlias{}`
```
[SEVERE] built_value_generator|built_value on lib/ToAlias.dart:
Unknown error in BuiltValueGenerator for builtvaluetest|lib/ToAlias.dart.
NoSuchMethodError: The getter 'displayName' was called on null.
Receiver: null
Tried calling: displayName
[WARNING] built_value_generator|built_value on lib/ToAlias.dart:
Missing "part 'ToAlias.g.dart';".
```

**Comment by zoechi** [comment] 2018-12-10 10:15
Duplicate of #542

**Closed** 2018-12-10 10:38 UTC
